### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by InitRoot** [ehrishirajsharma/SwiftnessX#21]
How do one go about creating a table on the app?

**Comment by FransHBotes** [comment]
Perfect. Looking forward to the release. I've tried subscription to assist with the methodologies, anyway to get involved with that? I have some ideas.

**Comment by ehrishirajsharma** [comment]
Sorry for the delay in repo-access, I was bit inactive due to the year-end. I just sent you the invite, looking forward for your contributions. 👍 

I'm still warming-up from holidays and have plans to complete web-app checklist very soon. You can also get in touch on my Twitter account: https://twitter.com/ehrishiraj if you want to discuss any specifics.

**Comment by ehrishirajsharma** [comment]
Hi @InitRoot,

It is done with the latest release, however it still needs a lot of improvement. (there were a lot of issues with the original repo: https://github.com/dost/quilljs-table)


**Source:** https://github.com/ehrishirajsharma/SwiftnessX/commit/b4fbd5dd097164c926966e0d4a893a56db2881cd

I will create a separate issue to improve it.
